### ISSUE TITLE
Unable to resolve module `./artifacts/boot/index`

### ISSUE THREAD

**Issue by cyberid41** [GeekyAnts/react-native-seed#1]
hello, i installed new boilerplate RN seed using Typescript and i get error warning when start `react-native run-android`

![screenshot_20170930-110750](https://user-images.githubusercontent.com/5117289/31042342-e842a6c0-a5cf-11e7-8180-10f29a125712.png)

**Comment by shivrajkumar** [comment]
@cyberid41 Run `npm run build` and then `react-native run-android`

**Comment by cyberid41** [comment]
Thank @shivrajkumar  it's been working fine
