### ISSUE TITLE
ReactNativeSeed Biolerplate Code Error

### ISSUE THREAD

**Issue by URvesh109** [GeekyAnts/react-native-seed#3]
Bundling `index.android.js`  [development, non-minified, hmr disabled]  98.7% (296/298), failed.
error: bundling failed: "Unable to resolve module `./artifacts/boot/index` from `/home/urvesh/Downloads/react-native-boilerplate-mobx-typescript-RN/App.js`: could not resolve `/home/urvesh/Downloads/react-native-boilerplate-mobx-typescript-RN/artifacts/boot/index' as a folder: it did not contain a package, nor an index file"

**Comment by shivrajkumar** [comment]
#1

**Comment by URvesh109** [comment]
ok thanks brother

**Comment by URvesh109** [comment]
thks bro
