### ISSUE TITLE
how to access form data in LoginContainer login() function?

### ISSUE THREAD

**Issue by Talor-A** [GeekyAnts/react-native-seed#4]
hi, how can I get the login data (email and password) and use it in the login function to login with my server?

**Comment by shivrajkumar** [comment]
@Talor-A The data should be available with `form` i.e, `form.email` and `form.password`.

**Comment by Talor-A** [comment]
ah ok. is there any particular reason the form isn't using the `redux-form` onSubmit prop?

**Comment by shivrajkumar** [comment]
@Talor-A The `Form` component being used there is NativeBase component. onSubmit prop is not available to it. And we also wanted to add a Toast to show the error message for the form.

**Comment by Talor-A** [comment]
@shivrajkumar so to access email and password inside `LoginContainer` `login()` method I could put 

```js
const form = (
      <Form>
      ...
      </Form>
  )
return <Login loginForm={form} onLogin={() => this.login(form)} />
```

in my render() method? and then in login() method:

```js
  login = (form) => {
    console.warn(`Email: ${form.email}, Password: ${form.password}`)
    ...
  }
```

is this correct? I'm getting email and password undefined in the `console.warn` statement.

**Comment by shivrajkumar** [comment]
@Talor-A `email` and `password` data is not available with redux form. I was talking about mobX and MST variation. Sorry about the confusion. 
You can get the values using `onChange` function on Input and use them as needed.

**Comment by shmesa22** [comment]
Sdf da sadfasdf sdaf ads fase dada fasdf dsa fads fads as dfsd af sad fsad f
