### ISSUE TITLE
Can not run it on windows - React Native Boilerplate with Redux + Typescript generated

### ISSUE THREAD

**Issue by axcl** [GeekyAnts/react-native-seed#6]
D:\react-native-boilerplate-redux-typescript-master>npm start

ReactNativeSeed@1.0.0 start D:\react-native-boilerplate-redux-typescript-maste
r
npm run build && concurrently -r 'npm run watch' 'react-native-scripts start'
ReactNativeSeed@1.0.0 build D:\react-native-boilerplate-redux-typescript-maste
r
npm run clean && npm run tsc --
ReactNativeSeed@1.0.0 clean D:\react-native-boilerplate-redux-typescript-maste
r
rimraf artifacts
ReactNativeSeed@1.0.0 tsc D:\react-native-boilerplate-redux-typescript-master
tsc
'np' is not recognized as an internal or external command,
operable program or batch file.
'run' is not recognized as an internal or external command,
operable program or batch file.
'watch'' is not recognized as an internal or external command,
operable program or batch file.
'react-native-script' is not recognized as an internal or external command,
operable program or batch file.
'start'' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v6.11.3
npm ERR! npm v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ReactNativeSeed@1.0.0 start: npm run build && concurrently -r 'npm run watch' 'react-native-scripts start'
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ReactNativeSeed@1.0.0 start script 'npm run build && conc
urrently -r 'npm run watch' 'react-native-scripts start''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ReactNativeSeed packa
ge,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! npm run build && concurrently -r 'npm run watch' 'react-native-scri
pts start'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs ReactNativeSeed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls ReactNativeSeed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! D:\react-native-boilerplate-redux-typescript-master\npm-debug.log

D:\react-native-boilerplate-redux-typescript-master>`

Node version is 6..11.3
Npm version is 3.10.10

**Comment by shivrajkumar** [comment]
@axcl Make sure your Expo/CRNA setup is working.

**Comment by axcl** [comment]
Got it working issue was withbthe environment path of npm

**Comment by homo7sapiens** [comment]
I fixed it after replacing ' with \" at each script with "concurrently"
"npm run build && concurrently -r \"npm run watch\" \"react-native-scripts start\""
