### ISSUE TITLE
Error with fresh build of typescript/redux/CRNA

### ISSUE THREAD

**Issue by whaus7** [GeekyAnts/react-native-seed#7]
Tried switched to ntypescript since tsc is deprecated but got the exactly same error even after switching? Been banging my head for 6 hours. Desperately need help..

> ReactNativeSeed@1.0.0 tsc /Users/whausman/PhpstormProjects/Warehouse_App_JSX
> tsc

src/boot/setup.tsx(18,3): error TS2554: Expected 1-2 arguments, but got 0.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ReactNativeSeed@1.0.0 tsc: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the ReactNativeSeed@1.0.0 tsc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/whausman/.npm/_logs/2017-11-17T23_02_25_941Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ReactNativeSeed@1.0.0 build: `npm run clean && npm run tsc --`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the ReactNativeSeed@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/whausman/.npm/_logs/2017-11-17T23_02_25_957Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ReactNativeSeed@1.0.0 start: `npm run build && concurrently -r 'npm run watch' 'react-native-scripts start'`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the ReactNativeSeed@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/whausman/.npm/_logs/2017-11-17T23_02_25_974Z-debug.log

**Comment by shivrajkumar** [comment]
@whaus7 The issue seems to be in line 18 of src/boot/setup.tsx as mentioned above
It should be 
```
constructor(props) {
    super(props);
    this.state = {
      isLoading: false,
      store: configureStore(() => this.setState({ isLoading: false })),
      isReady: false
    };
  }
```

**Comment by whaus7** [comment]
dude thanks! that did the trick. so should I be grabbing the repo from here or reactnativeseeds.com little setup wizard thing? to get the latest dependencies that is

**Comment by shivrajkumar** [comment]
@whaus7 Grab it from reactnativeseed.com
